name: sync-with-upstream

on:
  schedule:
    - cron: "43 06 * * *"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: jeremyd2019-repo-sync
    - run: |
        git remote add upstream https://sourceware.org/git/binutils-gdb.git
        git fetch -f upstream 'refs/heads/*:refs/heads/*' 'refs/tags/*:refs/tags/*'
        git push -f origin 'refs/heads/*:refs/heads/*' 'refs/tags/*:refs/tags/*'
